---
- id: check-poetry
  name: Poetry check
  description: Validates the structure of the pyproject.toml file
  entry: poetry check
  language: system
  pass_filenames: false
  files: pyproject.toml

- id: check-gitlab-ci
  name: GitLab CI/CD configuration check
  description: Validates .gitlab-ci.yml file
  entry: pre_commit_hooks/check-gitlab-ci
  language: script
  pass_filenames: false
  files: .gitlab-ci.yml
